name: Upload PyTest cache

description: Uploads the pytest cache to S3

inputs:
  cache_dir:
    description: Path to the pytest cache directory, relative to $GITHUB_WORKSPACE. This folder will be zipped and uploaded to S3.
    required: true
  shard:
    description: Shard number for the current job
    required: false
    default: "0"
  job_identifier:
    description: Text that uniquely identifies a given job type within a workflow. All shards of a job should share the same job identifier.
    required: true
  github-token:
    description: GITHUB_TOKEN
    required: true

runs:
  using: composite
  steps:
    - uses: nick-fields/retry@3e91a01664abd3c5cd539100d10d33b9c5b68482
      name: Setup dependencies
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        shell: bash
        timeout_minutes: 5
        max_attempts: 5
        retry_wait_seconds: 30
        command: |
          set -eu
          python3 -m pip install boto3==1.19.12

    - name: Upload the cache
      shell: bash
      env:
        CACHE_DIR: ${{ inputs.cache_dir }}
        JOB_IDENTIFIER: ${{ inputs.job_identifier }}
        SHARD: ${{ inputs.shard }}
      run: |
        set -eux

        echo "all the commands sent to the below script:"
        echo "cache_dir: $GITHUB_WORKSPACE/$CACHE_DIR"
        echo "pr_identifier: $GITHUB_REF"
        echo "JOB_IDENTIFIER: $JOB_IDENTIFIER"
        echo "shard: $SHARD"
        echo "temp_dir: $RUNNER_TEMP"

        python3 .github/scripts/pytest_cache.py \
          --upload \
          --cache_dir $GITHUB_WORKSPACE/$CACHE_DIR \
          --pr_identifier $GITHUB_REF \
          --job_identifier $JOB_IDENTIFIER \
          --shard $SHARD \
          --temp_dir $RUNNER_TEMP \