name: Download PyTest cache

description: Downloads the pytest cache to S3

inputs:
  cache_dir:
    description: Path to the pytest cache directory, relative to $GITHUB_WORKSPACE. This is where the merged cache will be placed.
    required: true
  build_environment:
    description: The build environment
    required: true
  github-token:
    description: GITHUB_TOKEN
    required: true

runs:
  using: composite
  steps:
    - uses: nick-fields/retry@3e91a01664abd3c5cd539100d10d33b9c5b68482
      name: Setup dependencies
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        shell: bash
        timeout_minutes: 5
        max_attempts: 5
        retry_wait_seconds: 30
        command: |
          set -eux
          python3 -m pip install boto3==1.19.12

    - name: Download the cache
      shell: bash
      env:
        CACHE_DIR: ${{ inputs.cache_dir }}
        JOB_IDENTIFIER: ${{ github.workflow }}_${{ github.job }}_${{ inputs.build_environment }}
        SHARD: ${{ inputs.shard }}
      run: |
        set +x

        echo "all the commands sent to the below script:"
        echo "cache_dir: $GITHUB_WORKSPACE/$CACHE_DIR"
        echo "pr_identifier: $GITHUB_REF"
        echo "JOB_IDENTIFIER: $JOB_IDENTIFIER"
        echo "shard: $SHARD"
        echo "temp_dir: $RUNNER_TEMP"


        python3 .github/scripts/pytest_cache.py \
          --download \
          --cache_dir $GITHUB_WORKSPACE/$CACHE_DIR \
          --pr_identifier $GITHUB_REF \
          --job_identifier $JOB_IDENTIFIER \
          --temp_dir $RUNNER_TEMP \